services:
  fga:
    image: openfga/openfga
    command: "run"
    restart: always
    ports:
      - "8080:8080"
      - "8081:8081"
      - "3000:3000"
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: example
      POSTGRES_PASSWORD: example
      POSTGRES_DB: example
    ports:
      - "5432:5432"

volumes:
  postgres_data: {}
